version: '3.6'

services:
  redis:
    image: redis
    # volumes:
    #   - /redis:/root/redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    restart: on-failure
  yagna:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.yagna
    ports:
      - '7477:7477'
    expose:
      - '7477'
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - yagna
    volumes:
      - ./src:/usr/src/app/src
    restart: on-failure
