version: '3.6'

services:
  redis:
    image: redis
    # volumes:
    #   - /redis:/root/redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    restart: on-failure
  yagna:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.yagna
    ports:
      - '7477:7477'
    expose:
      - '7477'
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENCRYPTION_KEY: 51a800c09e9f9baf999d48bbd871d392f1c12df8c9687efe10ddab45ec3d8833
      ENCRYPTION_IV: 9e07ce2856e1edfa91535cdd660d5721
    depends_on:
      - redis
      - yagna
    volumes:
      - ./src:/usr/src/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
